spring.application.name=ecommerce

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate related setting
# =============================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Spring security related setting
# =============================================================
# spring.security.user.name=admin
# spring.security.user.password=admin



spring.app.jwtSecret=dhsgfhsdgfhgdfhdgfhdgfhdfghghgryteyetrhsgdgdsdfsgfdsgdfsgdfsgfdsgfd
spring.app.jwtExpirationMs=604800000


razorpay.key=rzp_test_S060WMnc2eFoWe
razorpay.secret=4XRX50lBHOXxPQ9Nwlrb6HxU


